post http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmFzIiwiaWQiOiI1ZDkwZTU0ZWZiOTgxMDFmYzAwZjU5Y2YiLCJpYXQiOjE1Njk4NjY4NTF9.zneTGV6n3_Af1NLoqYUFAwkJ2PVz0luNffS1mhZJ1wg

{
        "title": "Blog post title",
        "author": "Blog author",
        "url": "https://www.blog.com",
        "likes": "3"
}